# Generated by Django 6.0.4 on 2026-05-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.CharField(default='note', max_length=10),
        ),
    ]
