# Generated by Django 6.0.4 on 2026-05-11 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_todoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='completed',
            new_name='is_done',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='type',
            field=models.CharField(choices=[('note', 'Note'), ('todo', 'Todo')], default='note', max_length=10),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='notes.note'),
        ),
    ]
